name: Build on Push
on: [push]
jobs:
  build:
    name: Build go sources
    runs-on: ubuntu-latest
    steps:

    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}   
    
    - uses: mr-smithers-excellent/docker-build-push@v2
      with:
        image: guftall/database2-final-project/backend
        tag: latest
        registry: docker.pkg.github.com
        dockerfile: Dockerfile
        username: ${{secrets.GITHUB_PKG_REGISTRY_USERNAME}}
        password: ${{secrets.GITHUB_PKG_REGISTRY_PASSWORD}}